apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: web-app
    annotations:
        kubernetes.io/ingress.global-static-ip-name: "wizard-0x65-app"
        networking.gke.io/managed-certificates: "web-app-certificate"
        kubernetes.io/ingress.class: "gce"
        networking.gke.io/v1.FrontendConfig: "default-redirect-config"
spec:
    rules:
        - host: team1.cs144.org
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: web-app
                            port:
                                number: 80
